### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by ericghaly** [sammytrhodes/ExamHelper#10]
Related Epic: Logout
Description: Logout
Done Means: The user can logout and nobody can view their questions.

**Comment by ghost** [comment]
Added logout buttons onto fxml windows with every window necessary. (3hrs)

**Comment by ghost** [comment]
Logout feature emulates code for Login, but returns false when user needs to exit. Code is not used for project but can still function without it. (2 hrs.)

**Comment by ghost** [comment]
This does work, but our team decided not to implement this into the final project since there would be time constraints involved. We needed a system that would work seamlessly and we gave priority towards working with Java FX, SQLite, interface functionality, etc.
