### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by sammytrhodes** [sammytrhodes/ExamHelper#16]
Epic: question repository
Definition: This will hold all of the questions for exams.
Definition of Done: questions will be organized by, question, answer and subject. They should have a unique identifier.

**Comment by davmarcella** [comment]
spent an hour creating initial database and starting addQuestion function

**Comment by davmarcella** [comment]
spent 30 minutes working on database stuff (syntax and mysql issues)

**Comment by davmarcella** [comment]
spent an hour and a half continuing to work on addQuestion. Should now only create the tables if they don't already exist. Next step is to get the number of items in each relation and use that number+1 as the new ID (primary key) for the question/subject being added

**Comment by davmarcella** [comment]
spent 30-40 minutes working on making sure ID's increment automatically and making sure duplicates cannot be added even though they'll have different ID's

**Comment by davmarcella** [comment]
spent 30 - 40 minutes discovering what characters will cause errors in sqlite and creating unit tests to prevent this

**Comment by davmarcella** [comment]
spent 40 minutes working on database helper file. Now creates tables and can populate them but getting an error when adding user inputted questions.

**Comment by davmarcella** [comment]
spent an additional 45 minutes completing the database helper file

**Comment by davmarcella** [comment]
spent 50 minutes adding a delete all function which removes everything from the database (good for testing), and fixed issue with addQuestion function. Now ready for integration with controller and interface.

**Comment by davmarcella** [comment]
spent 45 minutes creating valid integration tests in which it passed

**Comment by davmarcella** [comment]
spent 20 minutes adding getSubjects() function to give a List of all the subject Strings

**Comment by davmarcella** [comment]
spent 30 minutes:
added valid(int numQues, String subject) that checks to make sure a requested number of questions for any given subject exists. If someone requests an exam of 10 Algorithms questions, we want to make sure that there are enough questions to create that exam.

**Comment by davmarcella** [comment]
spent 35 minutes creating:
public static ArrayList<String> getQuestions(int numQues, String subject);
in database helper file

**Comment by davmarcella** [comment]
spent 1.5 hours:
working on creating Unit Tests (I know that should have been done sooner)
