### ISSUE TITLE
Choice interface

### ISSUE THREAD

**Issue by sammytrhodes** [sammytrhodes/ExamHelper#20]
Epic: 
Description: user interface that offers user choice between exporting exam or importing question(s).
Definition of Done: When called, interface opens and displays a prompt as well as buttons for exam export and question import.

**Comment by lbarry23** [comment]
Spent 1.5 hours creating simple interface with 3 unresponsive buttons.

**Comment by davmarcella** [comment]
translated into javafxml file and now done
