### ISSUE TITLE
Create Exam interface

### ISSUE THREAD

**Issue by sammytrhodes** [sammytrhodes/ExamHelper#21]
Epic: 
Description:
Definition of Done:

**Comment by lbarry23** [comment]
spent 2 hours working on exam interface. Cannot get the screen to load, project breaks on line "Parent loadScreen = (Parent) myLoader.load();" in ScreenController.java

**Comment by davmarcella** [comment]
spent 1.5 hours
fixed screen loading issue, added the number of questions field, added dB function to make sure the number of questions requested exists

**Comment by davmarcella** [comment]
15 minutes connecting newly created dB function getQuestions() to  interface function generateExam()

**Comment by davmarcella** [comment]
spent 30 minutes implementing logging system log4j and adding the jar file accordingly. Now uses logging rather than sysout. Commited to branch

**Comment by davmarcella** [comment]
spent 1 hour:
trying to figure out how to hide everything in interface and display a new label for error messages. This was unsuccessful so I quickly just created a new interface file called "InvalidExam"
