### ISSUE TITLE
Question choice interface

### ISSUE THREAD

**Issue by sammytrhodes** [sammytrhodes/ExamHelper#22]
Epic: As the instructor, I want to create exam for questions to be linked their specific topics.
Definition: Provides the user a choice between entering a single question or a file input containing the questions. 
Definitions of Done: There should be 2 buttons that will ask if the user would like to input a file or a singular question.

**Comment by lbarry23** [comment]
Spent 30 minutes creating a simple interface with two unresponsive buttons:
"Import Single Question" and "Import From File"

**Comment by davmarcella** [comment]
translated into javafxml file and now done
