### ISSUE TITLE
Create Controller

### ISSUE THREAD

**Issue by sammytrhodes** [sammytrhodes/ExamHelper#23]
done: when all interfaces are connected and running through the controller

**Comment by davmarcella** [comment]
physically created controller and merging choice interface with it

**Comment by davmarcella** [comment]
SIGNIFICANTLY harder to create instances of interfaces in a controller class

**Comment by davmarcella** [comment]
Every interface class (java and fxml file) should each have own controller started by one main controller "ScreensFramework.java"
