### ISSUE TITLE
Work on managing multiple screen for javaFX and controller

### ISSUE THREAD

**Issue by lbarry23** [sammytrhodes/ExamHelper#28]
Description: Need to figure out how to manage multiple screens

Def of Done: Can successfully manage multiple screens and can start working on controller

**Comment by davmarcella** [comment]
found video to review to try and work on this:
https://www.youtube.com/watch?v=5GsdaZWDcdY

**Comment by davmarcella** [comment]
spent an hour and 20 minutes with Sam working on trying to figure out multiple screens

**Comment by sammytrhodes** [comment]
spend an hour and 20 minutes with David, trying to connect multiple screens for our interface.

**Comment by davmarcella** [comment]
spent 30-40 minutes trying to figure out why javafx keeps crashing. Found out that when refactoring (renaming) the controller file, it doesn't change the name of it where it's referenced in the physical fxml code

**Comment by davmarcella** [comment]
spent 45 minutes trying to figure out structure of screens and controllers. Found github repo that helps a lot

**Comment by davmarcella** [comment]
spent 40 minutes figuring out how to make everything work. Can now phase through the screens and fixed the screen re-size issue

**Comment by lbarry23** [comment]
spent an hour and 30 minutes working on getting familiar with screen builder and understanding how screens are connected
