### ISSUE TITLE
Create Exam text file

### ISSUE THREAD

**Issue by ericghaly** [sammytrhodes/ExamHelper#3]
Related Epic: Create exam
Description: Create exam
Done means: Exam is created and can be accessed by user

**Comment by lbarry23** [comment]
spent an 1.5 hours
"Exam.txt" is generated when the user inputs subject and number of questions into CreateExam Interface. Subject is displayed at the top with name and date slots and questions are numbered and listed below.
Next step would be to get the file to open in a text editor or something

**Comment by davmarcella** [comment]
spent 30 minutes:
exam will now be titled "yyyy_mm_ddd-subject-exam.txt" so you can distinguish multiple exams rather than constantly writing over a single "Exam.txt"
Now when successfully created, exam automatically opens in system's default text editor
